apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-sample
  namespace: mongodb
spec:
  members: 1
  version: 6.0.0-ent
  type: ReplicaSet
  security:
    authentication:
      enabled: true
      modes: ["SCRAM"]
    tls:
      ca: custom-ca # Ensure this ConfigMap contains the CA certificate
      enabled: true
  authentication:
    enabled: true
    modes: ["X509"]
    internalCluster: "X509"
  additionalMongodConfig:
    net:
      tls:
        mode: "requireTLS"
  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials
  persistent: true
  podSpec:
    podTemplate:
      spec:
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "0.333"
                memory: "700Mi" # Added quotes around memory to ensure proper YAML parsing
